"""timestamps defaults

Revision ID: 1049f753e801
Revises: ff4e09a9fdf4
Create Date: 2026-01-18 19:22:49.598292

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1049f753e801'
down_revision: Union[str, Sequence[str], None] = 'ff4e09a9fdf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('slug'), table_name='lessons')
    op.drop_table('lessons')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons',
                    sa.Column('slug', mysql.VARCHAR(length=255), nullable=False),
                    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
                    sa.Column('body_markdown', mysql.TEXT(), nullable=False),
                    sa.Column('expected_output', mysql.TEXT(), nullable=False),
                    sa.Column('created_at', mysql.DATETIME(), nullable=False),
                    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
                    sa.Column('id', mysql.CHAR(length=32), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_index(op.f('slug'), 'lessons', ['slug'], unique=True)
    # ### end Alembic commands ###
