"""lesson order

Revision ID: c98807ed4d76
Revises: 1049f753e801
Create Date: 2026-01-18 21:14:42.556416

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'c98807ed4d76'
down_revision: Union[str, Sequence[str], None] = '1049f753e801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
