"""init

Revision ID: ff4e09a9fdf4
Revises: a5f9d6c593d2
Create Date: 2026-01-18 18:21:02.202970

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'ff4e09a9fdf4'
down_revision: Union[str, Sequence[str], None] = 'a5f9d6c593d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
