"""default_executor

Revision ID: 5924f24c7bd7
Revises: c695af9e7681
Create Date: 2026-01-26 21:17:17.490793

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '5924f24c7bd7'
down_revision: Union[str, Sequence[str], None] = 'c695af9e7681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
