"""remove legacy

Revision ID: 7a9b4c7f9140
Revises: 037cb3c6b0be
Create Date: 2026-01-26 19:35:10.620162

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7a9b4c7f9140'
down_revision: Union[str, Sequence[str], None] = '037cb3c6b0be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'eval_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'lessons', sa.Column(
            'eval_key', mysql.VARCHAR(length=128), server_default=sa.text("'lesson_01'"), nullable=False
            )
        )
    # ### end Alembic commands ###
