"""remove expected output

Revision ID: c695af9e7681
Revises: 7a9b4c7f9140
Create Date: 2026-01-26 21:02:25.338651

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c695af9e7681'
down_revision: Union[str, Sequence[str], None] = '7a9b4c7f9140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'expected_output')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('expected_output', mysql.TEXT(), nullable=False))
    # ### end Alembic commands ###
